<?xml version="1.0" encoding="UTF-8"?>
<!--

    requestedattribute.xsl

    Takes a metadata aggregate and gives statistics about RequestedAttribute
    elements in UKf-registered SPs.

    Note that UKf metadata started using mdrpi:RegistrationInfo in 2012-09
    so statistics before that date cannot be generated by this script.

-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
    xmlns:mdrpi="urn:oasis:names:tc:SAML:metadata:rpi"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    version="1.0">

    <xsl:output method="text" omit-xml-declaration="yes"/>

    <xsl:template match="/md:EntitiesDescriptor">

        <xsl:variable name="sps" select="//md:EntityDescriptor
        	[descendant::mdrpi:RegistrationInfo/@registrationAuthority='http://ukfederation.org.uk']
		[md:SPSSODescriptor]
		"/>
        <xsl:variable name="ACS" select="count($sps[md:SPSSODescriptor/md:AttributeConsumingService])"/>

	<xsl:value-of select="count($sps)"/>
        <xsl:text>&#09;</xsl:text>
	<xsl:value-of select="$ACS"/>
        <xsl:text>&#10;</xsl:text>

    </xsl:template>

</xsl:stylesheet>
